version: '3'

tasks:
  build:
    desc: Build the application
    cmds:
      - go build -o workctl main.go

  test:
    desc: Run tests
    cmds:
      - go test ./...

  setup:
    desc: Install required tools and dependencies
    cmds:
      - go mod download
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.64.5

  lint:
    desc: Run linters
    vars:
      GOBIN:
        sh: go env GOBIN
      GOPATH:
        sh: go env GOPATH
      LINT_BIN: "{{if .GOBIN}}{{.GOBIN}}{{else}}{{.GOPATH}}/bin{{end}}/golangci-lint"
    cmds:
      - "{{.LINT_BIN}} run"

  validate:
    desc: Validate the project
    deps: [lint, test, build]
